/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.my;


import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL; 
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import org.json.JSONObject;
import javax.swing.JTextArea;
import javax.swing.JTextField;
/**
 *
 * @author Adomas
 */
public class send_HTTP_Request extends javax.swing.JFrame {

    /**
     * Creates new form send_HTTP_Request
     */
    public send_HTTP_Request() {
        initComponents();
    }
    
    public static void call_me() throws Exception {
    String url = "http://api.ipinfodb.com/v3/ip-city/?key=b05f623f2754695f04479d03ae969c0c04a6581a95e57832a3614666b34157b3&ip=78.61.110.148&format=json";
    URL obj = new URL(url);
    HttpURLConnection con = (HttpURLConnection) obj.openConnection();
    con.setRequestMethod("GET");
    con.setRequestProperty("User-Agent", "Mozilla/5.0");
    //int responseCode = con.getResponseCode();
    //System.out.println("\nSending 'GET' request to URL : " + url);
    //System.out.println("Response Code : " + responseCode);
    BufferedReader in = new BufferedReader(
            new InputStreamReader(con.getInputStream()));
    String inputLine;
    StringBuffer response = new StringBuffer();
    while ((inputLine = in.readLine()) != null) {
    	response.append(inputLine);
    }
    in.close();
    //System.out.println(response.toString());
    JSONObject myResponse = new JSONObject(response.toString());
    //System.out.println("result after Reading JSON Response");
    //System.out.println("statusCode- "+myResponse.getString("statusCode"));
    //System.out.println("statusMessage- "+myResponse.getString("statusMessage"));
    JFrame f = new JFrame();
    JPanel p = new JPanel();
    p.setBounds(0,0,0,0); 
    JLabel tf1 = new JLabel();
    tf1.setBounds(40,50, 200, 30);
    JLabel tf2 = new JLabel();
    tf2.setBounds(40,80, 200, 30);
    JLabel tf3 = new JLabel();
    tf3.setBounds(40,110, 200, 30);
    JLabel tf4 = new JLabel();
    tf4.setBounds(40,140, 200, 30);
    JLabel tf5 = new JLabel();
    tf5.setBounds(40,170, 200, 30);
    JLabel tf6 = new JLabel();
    tf6.setBounds(40,200, 200, 30);
    JLabel tf7 = new JLabel();
    tf7.setBounds(40,230, 200, 30);
    JLabel tf8 = new JLabel();
    tf8.setBounds(40,260, 200, 30);
    JLabel tf9 = new JLabel();
    tf9.setBounds(40,290, 200, 30);
    tf1.setText("ipAddress-  "+myResponse.getString("ipAddress"));
    tf2.setText("countryCode-  "+myResponse.getString("countryCode"));
    tf3.setText("countryName-  "+myResponse.getString("countryName"));
    tf4.setText("regionName-  "+myResponse.getString("regionName"));
    tf5.setText("cityName-  "+myResponse.getString("cityName"));
    tf6.setText("zipCode-  "+myResponse.getString("zipCode"));
    tf7.setText("latitude-  "+myResponse.getString("latitude"));
    tf8.setText("longitude-  "+myResponse.getString("longitude"));
    tf9.setText("timeZone-  "+myResponse.getString("timeZone"));
    f.add(p);
    f.add(tf1);
    f.add(tf2);
    f.add(tf3);
    f.add(tf4);
    f.add(tf5);
    f.add(tf6);
    f.add(tf7);
    f.add(tf8);
    f.add(tf9);
    f.setSize(550, 550);
    f.setLocationRelativeTo(null);
    f.setLayout(null);    
    f.setVisible(true);
  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(send_HTTP_Request.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(send_HTTP_Request.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(send_HTTP_Request.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(send_HTTP_Request.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
	    send_HTTP_Request.call_me();
	}
        catch (Exception e) {
	    e.printStackTrace();
	}

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new send_HTTP_Request().setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
